// <auto-generated />
namespace Exam_Result.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class studentTblmodifiedagain : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentTblmodifiedagain));
        
        string IMigrationMetadata.Id
        {
            get { return "201907290433570_studentTbl modified again"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
